### ISSUE TITLE
com.ververica.cdc.debezium.Validator$$Lambda$25/1712669532@12f41634 is not serializable.

### ISSUE THREAD

**Issue by manmao** [ververica/flink-cdc-connectors#311]
当使用flink-cdc-postgres-2.0.0版本时，会报如下错误
`Exception in thread "main" org.apache.flink.api.common.InvalidProgramException: com.ververica.cdc.debezium.Validator$$Lambda$25/1712669532@12f41634 is not serializable. The object probably contains or references non serializable fields.
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:164)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:132)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:69)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.clean(StreamExecutionEnvironment.java:2000)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1685)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1668)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1637)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1623)
	at cdc.FlinkPgCdcStreamApiConnector.main(FlinkPgCdcStreamApiConnector.java:55)
Caused by: java.io.NotSerializableException: com.ververica.cdc.debezium.Validator$$Lambda$25/1712669532
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:624)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:143)
	... 8 more`

**Comment by leonardBang** [comment]
could you also post your code ? 
cc @fsk119

**Comment by izhangzhihao** [comment]
Same issue here `java.io.NotSerializableException: com.ververica.cdc.debezium.Validator$$Lambda$718/0x00000008404af840`

**Comment by leonardBang** [comment]
fixed in 3b26f6874240ccdb652c37d9a2efe04ee14f2fbd

**Comment by izhangzhihao** [comment]
Hi, I'm using Postgres source, just build from the master branch, still have the same issue...

**Comment by leonardBang** [comment]
@izhangzhihao Which commit are you building in master branch ? I just tried master is ok in 2bcf8a0dba5809c3bec56b791954bb9d7867fe22

**Comment by izhangzhihao** [comment]
Oh, to be clear, I build from this PR https://github.com/ververica/flink-cdc-connectors/pull/312

**Comment by izhangzhihao** [comment]
hi, just build from https://github.com/ververica/flink-cdc-connectors/commit/2bcf8a0dba5809c3bec56b791954bb9d7867fe22 and all works fine~
